services:
  - type: cron
    name: ig-reel-checker
    schedule: "0 */6 * * *"
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      python -m playwright install
    startCommand: python reelscraper.py
